"""update github_url to unique.

Revision ID: 494c6ff9852b
Revises: 95f262df98bd
Create Date: 2026-06-27 13:59:01.331403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '494c6ff9852b'
down_revision: Union[str, Sequence[str], None] = '95f262df98bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'repository', ['github_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'repository', type_='unique')
    # ### end Alembic commands ###
