"""added github_email to users table

Revision ID: 50c3ccaabd42
Revises: 21b35b6f7453
Create Date: 2026-06-30 15:44:31.493887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50c3ccaabd42'
down_revision: Union[str, Sequence[str], None] = '21b35b6f7453'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_email', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'users', ['github_email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'github_email')
    # ### end Alembic commands ###
