"""removed github_email from users table

Revision ID: 61ab36c61bba
Revises: 50c3ccaabd42
Create Date: 2026-06-30 15:48:51.615890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61ab36c61bba'
down_revision: Union[str, Sequence[str], None] = '50c3ccaabd42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_github_email_key'), 'users', type_='unique')
    op.drop_column('users', 'github_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('users_github_email_key'), 'users', ['github_email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
