"""update users table

Revision ID: 99b4395bfd21
Revises: d396ffca559b
Create Date: 2026-06-30 15:15:22.623361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99b4395bfd21'
down_revision: Union[str, Sequence[str], None] = 'd396ffca559b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'github_username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'github_installation_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'github_installation_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('users', 'github_username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
