import asyncio
import uuid

from app.services.github_service import GitHubService
from app.services.git_service import GitService

async def main():
    github = GitHubService()

    token = await github.get_installation_token(
        143348832
    )

    git = GitService(
        r"C:\Users\shaur\AppData\Local\Temp\tmpj2r9m58m"
    )

    print("Current:")
    print(git.get_origin_url())

    authenticated = git.build_authenticated_url(token)

    print("Authenticated:")
    print(authenticated)

    git.set_origin_url(authenticated)

    print("Updated:")
    print(git.get_origin_url())

    branch = f"feature/nascent-{uuid.uuid4().hex[:8]}"

    git.create_branch(branch)
    print(f"Branch Name: {git.repo.active_branch.name}")

    git.push(branch, token)
    print("code pushed successfully!")

    token = await github.get_installation_token(143348832)

    url = await github.create_pull_request(
        installation_token=token,
        owner="shaurya-afk",
        repo="demo",
        title="Test PR",
        head=branch,
        base="main",
        body="Generated by Nascent",
    )

    print(url)

asyncio.run(main())